### ISSUE TITLE
总体不错

### ISSUE THREAD

**Issue by twhy** [Liqiaomiao/demos#1]
1. 但是少了一个 “一键登录” 按钮，要用 Chrome 开发工具的移动模式才能看到。
<img width="280" alt="qq20170611-190234 2x" src="https://user-images.githubusercontent.com/7459812/27010496-91a412c0-4ed8-11e7-966d-1aefe3a9d1ce.png">
2. 不同的作业不要公用一个 CSS 文件。比如可以新开一个文件  qqlogin.css。
3. input 的高度是 44px，你的是 42px

**Comment by Liqiaomiao** [comment]
增加“一键登录”，css已重建，input高度已改，谢谢tom老师
